language: go
go:
  - 1.5
sudo: false
install:
  - go get -u github.com/golang/lint/golint
  - go get github.com/tools/godep
  - go install github.com/GeertJohan/go.rice/rice

script:
  - make build
  - make start &
  - curl http://localhost:8080
notifications:
